#!/bin/sh

## Operating system tool
## Main function
os() {
  arg=$1
  shift 1
  case $arg in
    backup)
      __os_backup
      ;;
    info)
      __os_info
      ;;
    update)
      __os_update $@
      ;;
    *)
      echo "os:: invalid arguments"
      echo "$arg"
      ;;
  esac
}

## Backup
## Save a snapshot of this machine to local and remote storage.
__os_backup() {
  echo "TODO: backup this machine"
}

## Info
## Print system information
__os_info() {
  echo "TODO: print system info"
  uptime | egrep -o 'up.*(([0-9]:[0-9][0-9])|(mins))'
}

## Update
## Check for updates to all monitored codebases.
__os_update() {
  echo "TODO: check for updates"
  up

  if [[ $1 ]] ; then
    echo $1
  fi  
}

up() {
  # TODO: check other package managers (brew) for updates
  # TODO: create a priority list with the update commands
  #   - loop thru, for each do
  #     - check program exists
  #     - update repositories, if applicable
  #     - check for software / package updates
  #     - if any, prompt user to select updates to install
  #     - install selected updates
  softwareupdate -l
  echo "TODO: Check for updates to xcode-select"
  echo "TODO: Check brew for updates"
  echo "\nApp Store Updates\n"
  mas list
}

## Install
## To make a fresh setup familiar.
## TODO: Everything
##       - Install personal git repos
##       - Install brew
##       - Install brew packages
##       - Install command line tools
##       - Install Xcode
##       - 
__os_install() {
  # TODO: 
  echo "TODO: write the install script!"
  echo "TODO: jk, this needs to be a standalone executable"
  echo "      ... if it is meant to install everything else."
  echo "      ... it can't require anything else."
}
